import { DocPage, P, H2, H3, UL, CodeBlock, Callout, Strong, InlineCode, Link2, Table } from "../../DocPage";
import { buildMetadata } from "@/lib/seo";

export const metadata = buildMetadata({
  title: "Opcodes & Status Codes",
  description:
    "SerikaCord Gateway opcodes, Gateway close codes, HTTP status codes, and JSON error codes. Complete reference for all API and Gateway codes.",
  path: "/developers/docs/topics/opcodes-and-status-codes",
  keywords: ["SerikaCord opcodes", "status codes", "error codes", "gateway close codes", "HTTP status"],
});

export default function OpcodesDoc() {
  return (
    <DocPage title="Opcodes & Status Codes" description="Gateway opcodes, close codes, and HTTP status codes used by the SerikaCord API.">
      <H2 id="gateway-opcodes">Gateway Opcodes</H2>
      <Table headers={["Opcode", "Name", "Direction", "Description"]} rows={[
        ["0", "Dispatch", "Server→Client", "Dispatches an event"],
        ["1", "Heartbeat", "Client→Server", "Maintains connection"],
        ["2", "Identify", "Client→Server", "Initial authentication"],
        ["3", "Presence Update", "Client→Server", "Update presence"],
        ["4", "Voice State Update", "Client→Server", "Join/leave voice"],
        ["5", "Resume", "Client→Server", "Resume missed events"],
        ["6", "Reconnect", "Server→Client", "Server requests reconnect"],
        ["7", "Request Guild Members", "Client→Server", "Request member info"],
        ["8", "Invalid Session", "Server→Client", "Session invalidated"],
        ["9", "Hello", "Server→Client", "Heartbeat interval"],
        ["10", "Heartbeat ACK", "Server→Client", "Heartbeat acknowledged"],
        ["11", "Request Soundboard Sounds", "Client→Server", "Request soundboard sounds"],
      ]} />

      <H2 id="gateway-close-codes">Gateway Close Codes</H2>
      <Table headers={["Code", "Description", "Can Resume?"]} rows={[
        ["4000", "Unknown error", "Yes"],
        ["4001", "Unknown opcode", "Yes"],
        ["4002", "Decode error", "Yes"],
        ["4003", "Not authenticated", "Yes"],
        ["4004", "Authentication failed", "No"],
        ["4005", "Already authenticated", "Yes"],
        ["4007", "Invalid seq", "Yes"],
        ["4008", "Rate limited", "Yes"],
        ["4009", "Session timed out", "Yes"],
        ["4010", "Invalid shard", "No"],
        ["4011", "Sharding required", "No"],
        ["4012", "Invalid API version", "No"],
        ["4013", "Invalid intent(s)", "No"],
        ["4014", "Disallowed intent(s)", "No"],
      ]} />

      <H2 id="http-status-codes">HTTP Status Codes</H2>
      <Table headers={["Code", "Name", "Description"]} rows={[
        ["200", "OK", "Request succeeded"],
        ["201", "Created", "Resource created"],
        ["204", "No Content", "Success, no body"],
        ["304", "Not Modified", "Cached resource still valid"],
        ["400", "Bad Request", "Malformed request"],
        ["401", "Unauthorized", "Missing/invalid auth token"],
        ["403", "Forbidden", "Lacking permissions"],
        ["404", "Not Found", "Resource doesn't exist"],
        ["405", "Method Not Allowed", "HTTP method not supported"],
        ["410", "Gone", "Resource permanently removed"],
        ["412", "Precondition Failed", "If-Match header not met"],
        ["429", "Too Many Requests", "Rate limited"],
        ["502", "Bad Gateway", "Server error"],
        ["5xx", "Server Error", "Internal server errors"],
      ]} />

      <H2 id="json-error-codes">JSON Error Codes</H2>
      <Table headers={["Code", "Name"]} rows={[
        ["0", "General error"],
        ["10001", "Unknown account"],
        ["10002", "Unknown application"],
        ["10003", "Unknown channel"],
        ["10004", "Unknown guild"],
        ["10005", "Unknown integration"],
        ["10006", "Unknown invite"],
        ["10007", "Unknown member"],
        ["10008", "Unknown message"],
        ["10009", "Unknown permission overwrite"],
        ["10010", "Unknown provider"],
        ["10011", "Unknown role"],
        ["10012", "Unknown token"],
        ["10013", "Unknown user"],
        ["10014", "Unknown emoji"],
        ["10015", "Unknown webhook"],
        ["10026", "Unknown ban"],
        ["10027", "Unknown SKU"],
        ["10028", "Unknown sticker"],
        ["10029", "Unknown sticker pack"],
        ["20001", "Bots cannot use this endpoint"],
        ["20002", "Only bots can use this endpoint"],
        ["30001", "Maximum number of guilds reached (100)"],
        ["30002", "Maximum number of friends reached"],
        ["30003", "Maximum number of pins reached"],
        ["30004", "Maximum number of recipients reached"],
        ["30005", "Maximum number of guild roles reached"],
        ["30007", "Maximum number of webhooks reached"],
        ["30008", "Maximum number of emojis reached"],
        ["30010", "Maximum number of reactions reached"],
        ["30011", "Maximum number of guild channels reached"],
        ["30013", "Maximum number of attachments in a message reached"],
        ["30015", "Maximum number of invites reached"],
        ["30016", "Maximum number of animated emojis reached"],
        ["30030", "Maximum number of guilds reached (200)"],
        ["40001", "Unauthorized"],
        ["40002", "You need to verify your account"],
        ["40003", "Opening direct messages too fast"],
        ["40004", "Send messages has been temporarily disabled"],
        ["40005", "Send messages in threads has been temporarily disabled"],
        ["40006", "Username has been changed too fast"],
        ["40007", "The resource is being rate limited"],
        ["40012", "Verification level too high"],
        ["50001", "Missing access"],
        ["50002", "Missing permissions"],
        ["50003", "Cannot edit a message authored by another user"],
        ["50004", "Cannot send an empty message"],
        ["50005", "Cannot send messages in a voice channel"],
        ["50006", "Channel verification level too high"],
        ["50007", "OAuth2 application does not have a bot"],
        ["50008", "OAuth2 application limit reached"],
        ["50009", "Invalid OAuth2 application"],
        ["50010", "Cannot delete a channel required for Community guilds"],
        ["50011", "Invalid action on Community guild"],
        ["50013", "Missing permissions (bitwise)"],
        ["50014", "Cannot execute action on a system message"],
        ["50015", "Cannot execute action on a channel type"],
        ["50016", "Invalid recipient(s)"],
        ["50017", "A message provided was too old to bulk delete"],
        ["50019", "A message can have max 40 reactions"],
        ["50021", "Cannot edit a message within a thread"],
        ["50024", "Cannot execute action on this server"],
        ["50025", "Cannot execute action on this channel type"],
        ["50033", "Invalid Recipient(s)"],
        ["50035", "Invalid form body"],
        ["50036", "An invite was accepted to a guild the application's bot is not in"],
        ["50041", "Invalid API version provided"],
        ["50045", "File uploaded exceeds the maximum size"],
        ["50046", "Invalid file uploaded"],
        ["50054", "Cannot self-redeem this gift"],
        ["50055", "Invalid guild"],
        ["50056", "Invalid message type"],
        ["50057", "Cannot pin a message in a thread"],
        ["50058", "Invalid channel type for invite"],
        ["50059", "Cannot delete a channel required for Community"],
        ["50070", "Cannot edit stickers within a message"],
        ["50074", "Invalid OAuth2 scope(s) provided"],
        ["50081", "Invalid sticker(s) provided"],
        ["50083", "Cannot update a completed event"],
        ["50084", "Cannot edit another user's event"],
        ["50085", "Cannot send stickers in a message"],
        ["50086", "Invalid action on guild scheduled event"],
        ["50095", "Unauthorized interaction"],
        ["50096", "Unauthorized application interaction"],
        ["50097", "Invalid interaction payload"],
        ["60003", "Two-factor authentication required"],
        ["80004", "No users with DiscordTag exist"],
        ["90001", "Reaction was blocked"],
        ["110001", "Cannot connect to voice channel"],
        ["110002", "Cannot send messages in a forum channel"],
        ["120001", "Cannot self-redeem this gift"],
        ["130001", "Cannot edit a message within a thread"],
        ["130002", "Cannot send messages in a thread"],
        ["130003", "Cannot create a thread in a forum channel"],
        ["130004", "Cannot edit a message in a thread"],
        ["130005", "Cannot delete a message in a thread"],
        ["130006", "Cannot pin a message in a thread"],
        ["130007", "Cannot add a reaction to a message in a thread"],
        ["130008", "Cannot remove a reaction from a message in a thread"],
        ["130009", "Cannot fetch a message in a thread"],
        ["160001", "Cannot edit a message within a thread"],
        ["160002", "Cannot send messages in a thread"],
        ["160003", "Cannot create a thread in a forum channel"],
        ["160004", "Cannot edit a message in a thread"],
        ["160005", "Cannot delete a message in a thread"],
        ["160006", "Cannot pin a message in a thread"],
        ["160007", "Cannot add a reaction to a message in a thread"],
        ["160008", "Cannot remove a reaction from a message in a thread"],
        ["160009", "Cannot fetch a message in a thread"],
        ["170001", "Cannot edit a message within a thread"],
        ["170002", "Cannot send messages in a thread"],
        ["170003", "Cannot create a thread in a forum channel"],
        ["170004", "Cannot edit a message in a thread"],
        ["170005", "Cannot delete a message in a thread"],
        ["170006", "Cannot pin a message in a thread"],
        ["170007", "Cannot add a reaction to a message in a thread"],
        ["170008", "Cannot remove a reaction from a message in a thread"],
        ["170009", "Cannot fetch a message in a thread"],
        ["180000", "Cannot edit a message within a thread"],
        ["180001", "Cannot send messages in a thread"],
        ["180002", "Cannot create a thread in a forum channel"],
        ["180003", "Cannot edit a message in a thread"],
        ["180004", "Cannot delete a message in a thread"],
        ["180005", "Cannot pin a message in a thread"],
        ["180006", "Cannot add a reaction to a message in a thread"],
        ["180007", "Cannot remove a reaction from a message in a thread"],
        ["180008", "Cannot fetch a message in a thread"],
        ["320000", "Cannot edit a message within a thread"],
        ["320001", "Cannot send messages in a thread"],
        ["320002", "Cannot create a thread in a forum channel"],
        ["320003", "Cannot edit a message in a thread"],
        ["320004", "Cannot delete a message in a thread"],
        ["320005", "Cannot pin a message in a thread"],
        ["320006", "Cannot add a reaction to a message in a thread"],
        ["320007", "Cannot remove a reaction from a message in a thread"],
        ["320008", "Cannot fetch a message in a thread"],
        ["350000", "Cannot edit a message within a thread"],
        ["350001", "Cannot send messages in a thread"],
        ["350002", "Cannot create a thread in a forum channel"],
        ["350003", "Cannot edit a message in a thread"],
        ["350004", "Cannot delete a message in a thread"],
        ["350005", "Cannot pin a message in a thread"],
        ["350006", "Cannot add a reaction to a message in a thread"],
        ["350007", "Cannot remove a reaction from a message in a thread"],
        ["350008", "Cannot fetch a message in a thread"],
        ["400000", "Cannot edit a message within a thread"],
        ["400001", "Cannot send messages in a thread"],
        ["400002", "Cannot create a thread in a forum channel"],
        ["400003", "Cannot edit a message in a thread"],
        ["400004", "Cannot delete a message in a thread"],
        ["400005", "Cannot pin a message in a thread"],
        ["400006", "Cannot add a reaction to a message in a thread"],
        ["400007", "Cannot remove a reaction from a message in a thread"],
        ["400008", "Cannot fetch a message in a thread"],
      ]} />

      <Callout type="info" title="Full Error Reference">
        These error codes mirror Discord's API exactly. The <InlineCode>code</InlineCode> field in
        error responses helps you programmatically handle errors.
      </Callout>
    </DocPage>
  );
}
