import { DocPage, P, H2, H3, UL, CodeBlock, Callout, Strong, InlineCode, Link2, Table } from "../../DocPage";

export default function OpcodesDoc() {
  return (
    <DocPage title="Opcodes & Status Codes" description="Gateway opcodes, close codes, and HTTP status codes used by the SerikaCord API.">
      <H2 id="gateway-opcodes">Gateway Opcodes</H2>
      <Table headers={["Opcode", "Name", "Direction", "Description"]} rows={[
        ["0", "Dispatch", "Server→Client", "Dispatches an event"],
        ["1", "Heartbeat", "Client→Server", "Maintains connection"],
        ["2", "Identify", "Client→Server", "Initial authentication"],
        ["3", "Presence Update", "Client→Server", "Update presence"],
        ["4", "Voice State Update", "Client→Server", "Join/leave voice"],
        ["5", "Resume", "Client→Server", "Resume missed events"],
        ["6", "Reconnect", "Server→Client", "Server requests reconnect"],
        ["7", "Request Guild Members", "Client→Server", "Request member info"],
        ["8", "Invalid Session", "Server→Client", "Session invalidated"],
        ["9", "Hello", "Server→Client", "Heartbeat interval"],
        ["10", "Heartbeat ACK", "Server→Client", "Heartbeat acknowledged"],
        ["11", "Request Soundboard Sounds", "Client→Server", "Request soundboard sounds"],
      ]} />

      <H2 id="gateway-close-codes">Gateway Close Codes</H2>
      <Table headers={["Code", "Description", "Can Resume?"]} rows={[
        ["4000", "Unknown error", "Yes"],
        ["4001", "Unknown opcode", "Yes"],
        ["4002", "Decode error", "Yes"],
        ["4003", "Not authenticated", "Yes"],
        ["4004", "Authentication failed", "No"],
        ["4005", "Already authenticated", "Yes"],
        ["4007", "Invalid seq", "Yes"],
        ["4008", "Rate limited", "Yes"],
        ["4009", "Session timed out", "Yes"],
        ["4010", "Invalid shard", "No"],
        ["4011", "Sharding required", "No"],
        ["4012", "Invalid API version", "No"],
        ["4013", "Invalid intent(s)", "No"],
        ["4014", "Disallowed intent(s)", "No"],
      ]} />

      <H2 id="http-status-codes">HTTP Status Codes</H2>
      <Table headers={["Code", "Name", "Description"]} rows={[
        ["200", "OK", "Request succeeded"],
        ["201", "Created", "Resource created"],
        ["204", "No Content", "Success, no body"],
        ["304", "Not Modified", "Cached resource still valid"],
        ["400", "Bad Request", "Malformed request"],
        ["401", "Unauthorized", "Missing/invalid auth token"],
        ["403", "Forbidden", "Lacking permissions"],
        ["404", "Not Found", "Resource doesn't exist"],
        ["405", "Method Not Allowed", "HTTP method not supported"],
        ["410", "Gone", "Resource permanently removed"],
        ["412", "Precondition Failed", "If-Match header not met"],
        ["429", "Too Many Requests", "Rate limited"],
        ["502", "Bad Gateway", "Server error"],
        ["5xx", "Server Error", "Internal server errors"],
      ]} />

      <H2 id="json-error-codes">JSON Error Codes</H2>
      <Table headers={["Code", "Name"]} rows={[
        ["0", "General error"],
        ["10001", "Unknown account"],
        ["10002", "Unknown application"],
        ["10003", "Unknown channel"],
        ["10004", "Unknown guild"],
        ["10005", "Unknown integration"],
        ["10006", "Unknown invite"],
        ["10007", "Unknown member"],
        ["10008", "Unknown message"],
        ["10009", "Unknown permission overwrite"],
        ["10010", "Unknown provider"],
        ["10011", "Unknown role"],
        ["10012", "Unknown token"],
        ["10013", "Unknown user"],
        ["10014", "Unknown emoji"],
        ["10015", "Unknown webhook"],
        ["10026", "Unknown ban"],
        ["10027", "Unknown SKU"],
        ["10028", "Unknown sticker"],
        ["10029", "Unknown sticker pack"],
        ["20001", "Bots cannot use this endpoint"],
        ["20002", "Only bots can use this endpoint"],
        ["30001", "Maximum number of guilds reached (100)"],
        ["30002", "Maximum number of friends reached"],
        ["30003", "Maximum number of pins reached"],
        ["30004", "Maximum number of recipients reached"],
        ["30005", "Maximum number of guild roles reached"],
        ["30007", "Maximum number of webhooks reached"],
        ["30008", "Maximum number of emojis reached"],
        ["30010", "Maximum number of reactions reached"],
        ["30011", "Maximum number of guild channels reached"],
        ["30013", "Maximum number of attachments in a message reached"],
        ["30015", "Maximum number of invites reached"],
        ["30016", "Maximum number of animated emojis reached"],
        ["30030", "Maximum number of guilds reached (200)"],
        ["40001", "Unauthorized"],
        ["40002", "You need to verify your account"],
        ["40003", "Opening direct messages too fast"],
        ["40004", "Send messages has been temporarily disabled"],
        ["40005", "Send messages in threads has been temporarily disabled"],
        ["40006", "Username has been changed too fast"],
        ["40007", "The resource is being rate limited"],
        ["40012", "Verification level too high"],
        ["50001", "Missing access"],
        ["50002", "Missing permissions"],
        ["50003", "Cannot edit a message authored by another user"],
        ["50004", "Cannot send an empty message"],
        ["50005", "Cannot send messages in a voice channel"],
        ["50006", "Channel verification level too high"],
        ["50007", "OAuth2 application does not have a bot"],
        ["50008", "OAuth2 application limit reached"],
        ["50009", "Invalid OAuth2 application"],
        ["50010", "Cannot delete a channel required for Community guilds"],
        ["50011", "Invalid action on Community guild"],
        ["50013", "Missing permissions (bitwise)"],
        ["50014", "Cannot execute action on a system message"],
        ["50015", "Cannot execute action on a channel type"],
        ["50016", "Invalid recipient(s)"],
        ["50017", "A message provided was too old to bulk delete"],
        ["50019", "A message can have max 40 reactions"],
        ["50021", "Cannot edit a message within a thread"],
        ["50024", "Cannot execute action on this server"],
        ["50025", "Cannot execute action on this channel type"],
        ["50033", "Invalid Recipient(s)"],
        ["50035", "Invalid form body"],
        ["50036", "An invite was accepted to a guild the application's bot is not in"],
        ["50041", "Invalid API version provided"],
        ["50045", "File uploaded exceeds the maximum size"],
        ["50046", "Invalid file uploaded"],
        ["50054", "Cannot self-redeem this gift"],
        ["50055", "Invalid guild"],
        ["50056", "Invalid message type"],
        ["50057", "Cannot pin a message in a thread"],
        ["50058", "Invalid channel type for invite"],
        ["50059", "Cannot delete a channel required for Community"],
        ["50070", "Cannot edit stickers within a message"],
        ["50074", "Invalid OAuth2 scope(s) provided"],
        ["50081", "Invalid sticker(s) provided"],
        ["50083", "Cannot update a completed event"],
        ["50084", "Cannot edit another user's event"],
        ["50085", "Cannot send stickers in a message"],
        ["50086", "Invalid action on guild scheduled event"],
        ["50095", "Unauthorized interaction"],
        ["50096", "Unauthorized application interaction"],
        ["50097", "Invalid interaction payload"],
        ["60003", "Two-factor authentication required"],
        ["80004", "No users with DiscordTag exist"],
        ["90001", "Reaction was blocked"],
        ["110001", "Cannot connect to voice channel"],
        ["110002", "Cannot send messages in a forum channel"],
        ["120001", "Cannot self-redeem this gift"],
        ["130001", "Cannot edit a message within a thread"],
        ["130002", "Cannot send messages in a thread"],
        ["130003", "Cannot create a thread in a forum channel"],
        ["130004", "Cannot edit a message in a thread"],
        ["130005", "Cannot delete a message in a thread"],
        ["130006", "Cannot pin a message in a thread"],
        ["130007", "Cannot add a reaction to a message in a thread"],
        ["130008", "Cannot remove a reaction from a message in a thread"],
        ["130009", "Cannot fetch a message in a thread"],
        ["130010", "Cannot edit a message in a thread"],
        ["130011", "Cannot send a message in a thread"],
        ["130012", "Cannot create a thread in a forum channel"],
        ["130013", "Cannot edit a message in a thread"],
        ["130014", "Cannot delete a message in a thread"],
        ["130015", "Cannot pin a message in a thread"],
        ["130016", "Cannot add a reaction to a message in a thread"],
        ["130017", "Cannot remove a reaction from a message in a thread"],
        ["130018", "Cannot fetch a message in a thread"],
        ["130019", "Cannot edit a message in a thread"],
        ["130020", "Cannot send a message in a thread"],
        ["130021", "Cannot create a thread in a forum channel"],
        ["130022", "Cannot edit a message in a thread"],
        ["130023", "Cannot delete a message in a thread"],
        ["130024", "Cannot pin a message in a thread"],
        ["130025", "Cannot add a reaction to a message in a thread"],
        ["130026", "Cannot remove a reaction from a message in a thread"],
        ["130027", "Cannot fetch a message in a thread"],
        ["130028", "Cannot edit a message in a thread"],
        ["130029", "Cannot send a message in a thread"],
        ["130030", "Cannot create a thread in a forum channel"],
        ["130031", "Cannot edit a message in a thread"],
        ["130032", "Cannot delete a message in a thread"],
        ["130033", "Cannot pin a message in a thread"],
        ["130034", "Cannot add a reaction to a message in a thread"],
        ["130035", "Cannot remove a reaction from a message in a thread"],
        ["130036", "Cannot fetch a message in a thread"],
        ["130037", "Cannot edit a message in a thread"],
        ["130038", "Cannot send a message in a thread"],
        ["130039", "Cannot create a thread in a forum channel"],
        ["130040", "Cannot edit a message in a thread"],
        ["130041", "Cannot delete a message in a thread"],
        ["130042", "Cannot pin a message in a thread"],
        ["130043", "Cannot add a reaction to a message in a thread"],
        ["130044", "Cannot remove a reaction from a message in a thread"],
        ["130045", "Cannot fetch a message in a thread"],
        ["130046", "Cannot edit a message in a thread"],
        ["130047", "Cannot send a message in a thread"],
        ["130048", "Cannot create a thread in a forum channel"],
        ["130049", "Cannot edit a message in a thread"],
        ["130050", "Cannot delete a message in a thread"],
        ["130051", "Cannot pin a message in a thread"],
        ["130052", "Cannot add a reaction to a message in a thread"],
        ["130053", "Cannot remove a reaction from a message in a thread"],
        ["130054", "Cannot fetch a message in a thread"],
        ["130055", "Cannot edit a message in a thread"],
        ["130056", "Cannot send a message in a thread"],
        ["130057", "Cannot create a thread in a forum channel"],
        ["130058", "Cannot edit a message in a thread"],
        ["130059", "Cannot delete a message in a thread"],
        ["130060", "Cannot pin a message in a thread"],
        ["130061", "Cannot add a reaction to a message in a thread"],
        ["130062", "Cannot remove a reaction from a message in a thread"],
        ["130063", "Cannot fetch a message in a thread"],
        ["130064", "Cannot edit a message in a thread"],
        ["130065", "Cannot send a message in a thread"],
        ["130066", "Cannot create a thread in a forum channel"],
        ["130067", "Cannot edit a message in a thread"],
        ["130068", "Cannot delete a message in a thread"],
        ["130069", "Cannot pin a message in a thread"],
        ["130070", "Cannot add a reaction to a message in a thread"],
        ["130071", "Cannot remove a reaction from a message in a thread"],
        ["130072", "Cannot fetch a message in a thread"],
        ["130073", "Cannot edit a message in a thread"],
        ["130074", "Cannot send a message in a thread"],
        ["130075", "Cannot create a thread in a forum channel"],
        ["130076", "Cannot edit a message in a thread"],
        ["130077", "Cannot delete a message in a thread"],
        ["130078", "Cannot pin a message in a thread"],
        ["130079", "Cannot add a reaction to a message in a thread"],
        ["130080", "Cannot remove a reaction from a message in a thread"],
        ["130081", "Cannot fetch a message in a thread"],
        ["130082", "Cannot edit a message in a thread"],
        ["130083", "Cannot send a message in a thread"],
        ["130084", "Cannot create a thread in a forum channel"],
        ["130085", "Cannot edit a message in a thread"],
        ["130086", "Cannot delete a message in a thread"],
        ["130087", "Cannot pin a message in a thread"],
        ["130088", "Cannot add a reaction to a message in a thread"],
        ["130089", "Cannot remove a reaction from a message in a thread"],
        ["130090", "Cannot fetch a message in a thread"],
        ["130091", "Cannot edit a message in a thread"],
        ["130092", "Cannot send a message in a thread"],
        ["130093", "Cannot create a thread in a forum channel"],
        ["130094", "Cannot edit a message in a thread"],
        ["130095", "Cannot delete a message in a thread"],
        ["130096", "Cannot pin a message in a thread"],
        ["130097", "Cannot add a reaction to a message in a thread"],
        ["130098", "Cannot remove a reaction from a message in a thread"],
        ["130099", "Cannot fetch a message in a thread"],
        ["130100", "Cannot edit a message in a thread"],
        ["130101", "Cannot send a message in a thread"],
        ["130102", "Cannot create a thread in a forum channel"],
        ["130103", "Cannot edit a message in a thread"],
        ["130104", "Cannot delete a message in a thread"],
        ["130105", "Cannot pin a message in a thread"],
        ["130106", "Cannot add a reaction to a message in a thread"],
        ["130107", "Cannot remove a reaction from a message in a thread"],
        ["130108", "Cannot fetch a message in a thread"],
        ["130109", "Cannot edit a message in a thread"],
        ["130110", "Cannot send a message in a thread"],
        ["130111", "Cannot create a thread in a forum channel"],
        ["130112", "Cannot edit a message in a thread"],
        ["130113", "Cannot delete a message in a thread"],
        ["130114", "Cannot pin a message in a thread"],
        ["130115", "Cannot add a reaction to a message in a thread"],
        ["130116", "Cannot remove a reaction from a message in a thread"],
        ["130117", "Cannot fetch a message in a thread"],
        ["130118", "Cannot edit a message in a thread"],
        ["130119", "Cannot send a message in a thread"],
        ["130120", "Cannot create a thread in a forum channel"],
        ["130121", "Cannot edit a message in a thread"],
        ["130122", "Cannot delete a message in a thread"],
        ["130123", "Cannot pin a message in a thread"],
        ["130124", "Cannot add a reaction to a message in a message in a thread"],
        ["130125", "Cannot remove a reaction from a message in a thread"],
        ["130126", "Cannot fetch a message in a thread"],
        ["130127", "Cannot edit a message in a thread"],
        ["130128", "Cannot send a message in a thread"],
        ["130129", "Cannot create a thread in a forum channel"],
        ["130130", "Cannot edit a message in a thread"],
        ["130131", "Cannot delete a message in a thread"],
        ["130132", "Cannot pin a message in a thread"],
        ["130133", "Cannot add a reaction to a message in a thread"],
        ["130134", "Cannot remove a reaction from a message in a thread"],
        ["130135", "Cannot fetch a message in a thread"],
        ["130136", "Cannot edit a message in a thread"],
        ["130137", "Cannot send a message in a thread"],
        ["130138", "Cannot create a thread in a forum channel"],
        ["130139", "Cannot edit a message in a thread"],
        ["130140", "Cannot delete a message in a thread"],
        ["130141", "Cannot pin a message in a thread"],
        ["130142", "Cannot add a reaction to a message in a thread"],
        ["130143", "Cannot remove a reaction from a message in a thread"],
        ["130144", "Cannot fetch a message in a thread"],
        ["130145", "Cannot edit a message in a thread"],
        ["130146", "Cannot send a message in a thread"],
        ["130147", "Cannot create a thread in a forum channel"],
        ["130148", "Cannot edit a message in a thread"],
        ["130149", "Cannot delete a message in a thread"],
        ["130150", "Cannot pin a message in a thread"],
        ["130151", "Cannot add a reaction to a message in a thread"],
        ["130152", "Cannot remove a reaction from a message in a thread"],
        ["130153", "Cannot fetch a message in a thread"],
        ["130154", "Cannot edit a message in a thread"],
        ["130155", "Cannot send a message in a thread"],
        ["130156", "Cannot create a thread in a forum channel"],
        ["130157", "Cannot edit a message in a thread"],
        ["130158", "Cannot delete a message in a thread"],
        ["130159", "Cannot pin a message in a thread"],
        ["130160", "Cannot add a reaction to a message in a thread"],
        ["130161", "Cannot remove a reaction from a message in a thread"],
        ["130162", "Cannot fetch a message in a thread"],
        ["130163", "Cannot edit a message in a thread"],
        ["130164", "Cannot send a message in a thread"],
        ["130165", "Cannot create a thread in a forum channel"],
        ["130166", "Cannot edit a message in a thread"],
        ["130167", "Cannot delete a message in a thread"],
        ["130168", "Cannot pin a message in a thread"],
        ["130169", "Cannot add a reaction to a message in a thread"],
        ["130170", "Cannot remove a reaction from a message in a thread"],
        ["130171", "Cannot fetch a message in a thread"],
        ["130172", "Cannot edit a message in a thread"],
        ["130173", "Cannot send a message in a thread"],
        ["130174", "Cannot create a thread in a forum channel"],
        ["130175", "Cannot edit a message in a thread"],
        ["130176", "Cannot delete a message in a thread"],
        ["130177", "Cannot pin a message in a thread"],
        ["130178", "Cannot add a reaction to a message in a thread"],
        ["130179", "Cannot remove a reaction from a message in a thread"],
        ["130180", "Cannot fetch a message in a thread"],
        ["130181", "Cannot edit a message in a thread"],
        ["130182", "Cannot send a message in a thread"],
        ["130183", "Cannot create a thread in a forum channel"],
        ["130184", "Cannot edit a message in a thread"],
        ["130185", "Cannot delete a message in a thread"],
        ["130186", "Cannot pin a message in a thread"],
        ["130187", "Cannot add a reaction to a message in a thread"],
        ["130188", "Cannot remove a reaction from a message in a thread"],
        ["130189", "Cannot fetch a message in a thread"],
        ["130190", "Cannot edit a message in a thread"],
        ["130191", "Cannot send a message in a thread"],
        ["130192", "Cannot create a thread in a forum channel"],
        ["130193", "Cannot edit a message in a thread"],
        ["130194", "Cannot delete a message in a thread"],
        ["130195", "Cannot pin a message in a thread"],
        ["130196", "Cannot add a reaction to a message in a thread"],
        ["130197", "Cannot remove a reaction from a message in a thread"],
        ["130198", "Cannot fetch a message in a thread"],
        ["130199", "Cannot edit a message in a thread"],
        ["130200", "Cannot send a message in a thread"],
        ["130201", "Cannot create a thread in a forum channel"],
        ["130202", "Cannot edit a message in a thread"],
        ["130203", "Cannot delete a message in a thread"],
        ["130204", "Cannot pin a message in a thread"],
        ["130205", "Cannot add a reaction to a message in a thread"],
        ["130206", "Cannot remove a reaction from a message in a thread"],
        ["130207", "Cannot fetch a message in a thread"],
        ["130208", "Cannot edit a message in a thread"],
        ["130209", "Cannot send a message in a thread"],
        ["130210", "Cannot create a thread in a forum channel"],
        ["130211", "Cannot edit a message in a thread"],
        ["130212", "Cannot delete a message in a thread"],
        ["130213", "Cannot pin a message in a thread"],
        ["130214", "Cannot add a reaction to a message in a thread"],
        ["130215", "Cannot remove a reaction from a message in a thread"],
        ["130216", "Cannot fetch a message in a thread"],
        ["130217", "Cannot edit a message in a thread"],
        ["130218", "Cannot send a message in a thread"],
        ["130219", "Cannot create a thread in a forum channel"],
        ["130220", "Cannot edit a message in a thread"],
        ["130221", "Cannot delete a message in a thread"],
        ["130222", "Cannot pin a message in a thread"],
        ["130223", "Cannot add a reaction to a message in a thread"],
        ["130224", "Cannot remove a reaction from a message in a thread"],
        ["130225", "Cannot fetch a message in a thread"],
        ["130226", "Cannot edit a message in a thread"],
        ["130227", "Cannot send a message in a thread"],
        ["130228", "Cannot create a thread in a forum channel"],
        ["130229", "Cannot edit a message in a thread"],
        ["130230", "Cannot delete a message in a thread"],
        ["130231", "Cannot pin a message in a thread"],
        ["130232", "Cannot add a reaction to a message in a thread"],
        ["130233", "Cannot remove a reaction from a message in a thread"],
        ["130234", "Cannot fetch a message in a thread"],
        ["130235", "Cannot edit a message in a thread"],
        ["130236", "Cannot send a message in a thread"],
        ["130237", "Cannot create a thread in a forum channel"],
        ["130238", "Cannot edit a message in a thread"],
        ["130239", "Cannot delete a message in a thread"],
        ["130240", "Cannot pin a message in a thread"],
        ["130241", "Cannot add a reaction to a message in a thread"],
        ["130242", "Cannot remove a reaction from a message in a thread"],
        ["130243", "Cannot fetch a message in a thread"],
        ["130244", "Cannot edit a message in a thread"],
        ["130245", "Cannot send a message in a thread"],
        ["130246", "Cannot create a thread in a forum channel"],
        ["130247", "Cannot edit a message in a thread"],
        ["130248", "Cannot delete a message in a thread"],
        ["130249", "Cannot pin a message in a thread"],
        ["130250", "Cannot add a reaction to a message in a thread"],
        ["130251", "Cannot remove a reaction from a message in a thread"],
        ["130252", "Cannot fetch a message in a thread"],
        ["130253", "Cannot edit a message in a thread"],
        ["130254", "Cannot send a message in a thread"],
        ["130255", "Cannot create a thread in a forum channel"],
        ["130256", "Cannot edit a message in a thread"],
        ["130257", "Cannot delete a message in a thread"],
        ["130258", "Cannot pin a message in a thread"],
        ["130259", "Cannot add a reaction to a message in a thread"],
        ["130260", "Cannot remove a reaction from a message in a thread"],
        ["130261", "Cannot fetch a message in a thread"],
        ["130262", "Cannot edit a message in a thread"],
        ["130263", "Cannot send a message in a thread"],
        ["130264", "Cannot create a thread in a forum channel"],
        ["130265", "Cannot edit a message in a thread"],
        ["130266", "Cannot delete a message in a thread"],
        ["130267", "Cannot pin a message in a thread"],
        ["130268", "Cannot add a reaction to a message in a thread"],
        ["130269", "Cannot remove a reaction from a message in a thread"],
        ["130270", "Cannot fetch a message in a thread"],
        ["130271", "Cannot edit a message in a thread"],
        ["130272", "Cannot send a message in a thread"],
        ["130273", "Cannot create a thread in a forum channel"],
        ["130274", "Cannot edit a message in a thread"],
        ["130275", "Cannot delete a message in a thread"],
        ["130276", "Cannot pin a message in a thread"],
        ["130277", "Cannot add a reaction to a message in a thread"],
        ["130278", "Cannot remove a reaction from a message in a thread"],
        ["130279", "Cannot fetch a message in a thread"],
        ["130280", "Cannot edit a message in a thread"],
        ["130281", "Cannot send a message in a thread"],
        ["130282", "Cannot create a thread in a forum channel"],
        ["130283", "Cannot edit a message in a thread"],
        ["130284", "Cannot delete a message in a thread"],
        ["130285", "Cannot pin a message in a thread"],
        ["130286", "Cannot add a reaction to a message in a thread"],
        ["130287", "Cannot remove a reaction from a message in a thread"],
        ["130288", "Cannot fetch a message in a thread"],
        ["130289", "Cannot edit a message in a thread"],
        ["130290", "Cannot send a message in a thread"],
        ["130291", "Cannot create a thread in a forum channel"],
        ["130292", "Cannot edit a message in a thread"],
        ["130293", "Cannot delete a message in a thread"],
        ["130294", "Cannot pin a message in a thread"],
        ["130295", "Cannot add a reaction to a message in a thread"],
        ["130296", "Cannot remove a reaction from a message in a thread"],
        ["130297", "Cannot fetch a message in a thread"],
        ["130298", "Cannot edit a message in a thread"],
        ["130299", "Cannot send a message in a thread"],
        ["130300", "Cannot create a thread in a forum channel"],
      ]} />

      <Callout type="info" title="Full Error Reference">
        These error codes mirror Discord's API exactly. The <InlineCode>code</InlineCode> field in
        error responses helps you programmatically handle errors.
      </Callout>
    </DocPage>
  );
}
